project_name: utils
before:
  hooks:
    - make test
    - make lint
release:
  github:
    owner: kubermatic
    name: utils
  prerelease: true
builds:
  - id: build-testjsonformat
    binary: testjsonformat
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/testjsonformat/main.go
archives:
  - id: kubecarrier
    builds:
      - kubecarrier
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
