presubmits:
  - name: pull-utils-test
    always_run: true
    decorate: true
    clone_uri: ssh://git@github.com/kubermatic/utils.git
    spec:
      containers:
        - image: quay.io/kubecarrier/test  # update to utils image once created
          imagePullPolicy: Always
          command:
            - go-init
            - -main
            - make test
          env:
            - name: GO111MODULE
              value: "on"
          resources:
            requests:
              cpu: 4
  - name: pull-utils-lint
    always_run: true
    decorate: true
    clone_uri: ssh://git@github.com/kubermatic/utils.git
    spec:
      containers:
        - image: quay.io/kubecarrier/dev:v5  # update to utils image once created
          imagePullPolicy: Always
          command:
            - go-init
            - -main
            - make lint
          env:
            - name: GO111MODULE
              value: "on"
          resources:
            requests:
              cpu: 4
              memory: 6Gi
